<?php
/**
 * My Local SEO – Docs: Shortcodes Auto Reference (Phase 3)
 * File: admin/docs/shortcodes-auto.php
 */

if ( ! defined('ABSPATH') ) exit;

require_once plugin_dir_path(__FILE__) . 'lib/shortcodes.php';

$q = isset($_GET['q']) ? sanitize_text_field( (string) $_GET['q'] ) : '';
$force = isset($_GET['refresh']) ? (int) $_GET['refresh'] : 0;

$items = mlseo_docs_build_shortcodes_index( $force === 1 );

// Search filter (name, summary, file)
if ( $q !== '' ) {
	$qq = strtolower($q);
	$items = array_values(array_filter($items, function($sc) use ($qq){
		$hay = strtolower(
			($sc['name'] ?? '') . ' ' .
			($sc['summary'] ?? '') . ' ' .
			($sc['file_rel'] ?? '')
		);
		return strpos($hay, $qq) !== false;
	}));
}

$export_md_url = wp_nonce_url(
	admin_url('admin-post.php?action=mlseo_docs_export_shortcodes_md'),
	'mlseo_docs_export_shortcodes'
);
$export_html_url = wp_nonce_url(
	admin_url('admin-post.php?action=mlseo_docs_export_shortcodes_html'),
	'mlseo_docs_export_shortcodes'
);

?>

<div style="display:flex;gap:16px;flex-wrap:wrap;align-items:center;justify-content:space-between;">
	<form method="get" action="" style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;">
		<input type="hidden" name="page" value="mlseo-docs" />
		<input type="hidden" name="tab" value="sc_auto" />
		<input type="text" name="q" value="<?php echo esc_attr($q); ?>" placeholder="Search shortcodes…" style="min-width:320px;" />
		<button class="button">Search</button>
		<a class="button" href="<?php echo esc_url( admin_url('admin.php?page=mlseo-docs&tab=sc_auto&refresh=1') ); ?>">Refresh Index</a>
	</form>

	<div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;">
		<a class="button button-primary" href="<?php echo esc_url($export_md_url); ?>">Export Markdown</a>
		<a class="button" href="<?php echo esc_url($export_html_url); ?>">Export HTML</a>
	</div>
</div>

<p style="margin-top:12px;">
	This page is generated by scanning <code>/modules/shortcodes/</code> for <code>add_shortcode()</code> calls and nearby docblocks.
	To improve the output, add a docblock above each shortcode or above its <code>add_shortcode()</code> call with example usage.
</p>

<hr />

<?php if ( empty($items) ): ?>
	<p><em>No shortcodes found.</em></p>
<?php else: ?>
	<p><strong><?php echo (int) count($items); ?></strong> shortcode(s) found.</p>

	<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:16px;">
		<?php foreach ( $items as $sc ): ?>
			<div style="border:1px solid #ccd0d4;border-radius:12px;padding:14px;background:#fff;">
				<div style="display:flex;align-items:baseline;justify-content:space-between;gap:10px;">
					<h3 style="margin:0;">[<?php echo esc_html($sc['name']); ?>]</h3>
					<small style="color:#646970;"><?php echo esc_html($sc['file_rel']); ?></small>
				</div>

				<?php if ( ! empty($sc['summary']) ): ?>
					<p style="margin:10px 0 0;"><?php echo esc_html($sc['summary']); ?></p>
				<?php endif; ?>

				<?php if ( ! empty($sc['examples']) ): ?>
					<div style="margin-top:10px;">
						<strong>Examples</strong>
						<?php foreach ( $sc['examples'] as $ex ): ?>
							<pre style="white-space:pre-wrap;background:#f6f7f7;border:1px solid #dcdcde;border-radius:10px;padding:10px;overflow:auto;"><code><?php echo esc_html($ex); ?></code></pre>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>

				<?php if ( ! empty($sc['attributes']) ): ?>
					<div style="margin-top:10px;">
						<strong>Attributes</strong>
						<ul style="margin:8px 0 0 18px;">
							<?php foreach ( $sc['attributes'] as $a ): ?>
								<li><code><?php echo esc_html($a); ?></code></li>
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endif; ?>

				<?php if ( ! empty($sc['notes']) ): ?>
					<div style="margin-top:10px;">
						<strong>Notes</strong>
						<ul style="margin:8px 0 0 18px;">
							<?php foreach ( $sc['notes'] as $n ): ?>
								<li><?php echo esc_html($n); ?></li>
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endif; ?>

				<?php if ( ! empty($sc['requires']) ): ?>
					<div style="margin-top:10px;">
						<strong>Requirements / Dependencies</strong>
						<ul style="margin:8px 0 0 18px;">
							<?php foreach ( $sc['requires'] as $r ): ?>
								<li><?php echo esc_html($r); ?></li>
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endif; ?>
			</div>
		<?php endforeach; ?>
	</div>
<?php endif; ?>
