<?php
// File: inc/assets.php
if ( ! defined('ABSPATH') ) exit;

/**
 * Returns true when we’re on the My Local SEO admin page.
 */
if ( ! function_exists('myls_is_admin_page') ) {
    function myls_is_admin_page(): bool {
        // Adjust 'my-local-seo' if your slug differs
        return is_admin() && isset($_GET['page']) && $_GET['page'] === 'my-local-seo';
    }
}

/**
 * Admin styles/scripts
 */
add_action('admin_enqueue_scripts', function( $hook ) {
    if ( ! myls_is_admin_page() ) return;

    // --- Bootstrap 5.3 (no jQuery dependency)
    $ver = '5.3.3';
    wp_enqueue_style(
        'myls-bootstrap',
        'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css',
        [],
        $ver
    );
    
    // Bootstrap Icons
    wp_enqueue_style(
        'myls-bootstrap-icons',
        'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css',
        [],
        '1.11.3'
    );

    wp_enqueue_script(
        'myls-popper',
        'https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js',
        [],
        '2.11.8',
        true
    );
    wp_enqueue_script(
        'myls-bootstrap',
        'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js',
        ['myls-popper'],
        $ver,
        true
    );

    // --- Minimal admin shim so Bootstrap + WP admin styles play nicely
    $shim = "
    /* Space the content a bit and keep Bootstrap cards readable in wp-admin */
    .myls-admin-wrap .card { border-radius: .5rem; }
    .myls-admin-wrap .card .card-header { font-weight: 600; }
    .myls-admin-wrap .form-control, .myls-admin-wrap .form-select { max-width: 100%; }
    .myls-admin-wrap .container-fluid { padding-left: 0; padding-right: 0; }
    .myls-admin-wrap details summary { cursor: pointer; }
    /* Keep WP nav tabs unchanged; our tab bodies can still use Bootstrap */
    .myls-admin-content .row { margin-left: 0; margin-right: 0; }
    ";
    wp_register_style('myls-admin-inline', false);
    wp_enqueue_style('myls-admin-inline');
    wp_add_inline_style('myls-admin-inline', $shim);

    // --- Prompt History Toolbar JS (shared across all AI tabs)
    $pt_ver = defined('MYLS_VERSION') ? MYLS_VERSION : time();
    wp_enqueue_script(
        'myls-prompt-toolbar',
        trailingslashit(MYLS_URL) . 'assets/js/myls-prompt-toolbar.js',
        [],
        $pt_ver,
        true
    );
    wp_add_inline_script(
        'myls-prompt-toolbar',
        'window.myls_prompt_toolbar_nonce = ' . wp_json_encode( wp_create_nonce('myls_ai_ops') ) . ';',
        'before'
    );

    // --- Enterprise Log Formatter (shared across all AI tabs) — load in header
    wp_enqueue_script(
        'myls-log-formatter',
        trailingslashit(MYLS_URL) . 'assets/js/myls-log-formatter.js',
        [],
        $pt_ver,
        false  // header, not footer — must load before inline subtab scripts
    );

    // --- Export Log to PDF (shared across all AI tabs)
    wp_enqueue_script(
        'myls-export-log',
        trailingslashit(MYLS_URL) . 'assets/js/myls-export-log.js',
        [],
        $pt_ver,
        true
    );
}, 20);

/**
 * Frontend: Enqueue Bootstrap Icons + Bootstrap CSS on pages generated by Page Builder.
 * These pages use Bootstrap 5 classes and Bootstrap Icons in their content.
 */
add_action('wp_enqueue_scripts', function() {
    if ( is_admin() ) return;

    // Only load on singular pages/posts that were generated by Page Builder
    if ( ! is_singular() ) return;

    $post_id = get_the_ID();
    if ( ! $post_id ) return;

    // Check if this post was generated by Page Builder OR if content contains bi- icons
    $is_pb_page = get_post_meta($post_id, '_myls_pb_generated', true);
    $is_sb_page = get_post_meta($post_id, '_myls_generated', true);

    if ( ! $is_pb_page && ! $is_sb_page ) {
        // Also check content for bootstrap classes as a fallback
        $content = get_post_field('post_content', $post_id);
        if ( strpos($content, 'bi bi-') === false && strpos($content, 'bootstrap') === false ) {
            return;
        }
    }

    // Bootstrap 5 CSS (only the CSS, not JS — lightweight)
    wp_enqueue_style(
        'myls-bootstrap-frontend',
        'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css',
        [],
        '5.3.3'
    );

    // Bootstrap Icons
    wp_enqueue_style(
        'myls-bootstrap-icons-frontend',
        'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css',
        [],
        '1.11.3'
    );

    // Bootstrap JS (needed for accordion, collapse, etc.)
    wp_enqueue_script(
        'myls-bootstrap-frontend-js',
        'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js',
        [],
        '5.3.3',
        true
    );
});
